spring.application.name=FlashlightDC
server.port=8080
frontend.url=${FRONTEND_URL:http://localhost:3000}
congress.api.key=${CONGRESS_API_KEY}
congress.api.base-url=https://api.congress.gov/v3
spring.task.scheduling.pool.size=5
ingestion.congress=119
ingestion.bill.cron=0 0 */3 * * *
ingestion.member.cron=0 30 */3 * * *
stats.computation.cron=0 0 1 * * *
stats.snapshot.cron=0 0 0 * * *
ingestion.summary.cron=0 0 * * * *
ingestion.bill.refresh=false
ingestion.member.refresh=false
# Oracle

spring.datasource.url=${DB_URL}
spring.datasource.username=flashlight_db
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect