spring.application.name=FlashlightDC
server.port=8080
frontend.url=${FRONTEND_URL:http://localhost:3000}
congress.api.key=${CONGRESS_API_KEY}
congress.api.base-url=https://api.congress.gov/v3

# Oracle
spring.datasource.url=jdbc:oracle:thin:@flashlightdc_medium
spring.datasource.username=flashlight_db
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect